# Generated by Django 5.0.3 on 2024-03-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_buku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=200)),
                ('nama_buku', models.CharField(max_length=200)),
                ('harga', models.DecimalField(decimal_places=3, max_digits=15)),
                ('stok', models.IntegerField()),
                ('penerbit', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('photo', models.ImageField(upload_to='images')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('employee_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('shipper_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id_penerbit', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('kota', models.CharField(max_length=200)),
                ('telepon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('supplier_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('unit', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
    ]
