# Generated by Django 5.0.3 on 2024-03-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
