# Generated by Django 5.0.3 on 2024-03-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('supplier_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('unit', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('photo', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
            ],
        ),
    ]
